env:
  browser: true
  es2021: true
  node: true
plugins:
  - html
  - css-modules 
extends: 
  - airbnb-base
  - plugin:css-modules/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
